version: '3.9'


services:

  db:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27000:27017"
  
  mongo_seed:
    image: mongo
    links:
      - mongodb
    volumes:
      - ./mongo_seed:/mongo_seed
    command:
      /mongo_seed/import.sh

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.1.3
    container_name: es
    command:
      - sysctl -w vm.max_map_count=262144 && su elasticsearch -c bin/elasticsearch
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
  
  web:
    image: gorsheninnikolay/intern_task
    restart: always
    container_name: my_application
    command: python main.py
    environment:
      - URL_ES=http://elasticsearch:9200
      - URL_DB=mongodb://db:27017
    ports:
      - "8080:8080"
    depends_on:
      - db
      - elasticsearch

